version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./data:/app/data