name: Deploy Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/platon-discord-bot:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: 1022
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script_stop: true
        timeout: 180s
        command_timeout: 60s
        script: |
          # 디렉토리 생성
          mkdir -p /home/${{ secrets.SERVER_USERNAME }}/platon-discord-bot
          cd /home/${{ secrets.SERVER_USERNAME }}/platon-discord-bot
          
          # docker-compose.yml 파일 생성
          cat > docker-compose.yml << EOL
          version: '3.8'
          
          services:
            bot:
              image: ${{ secrets.DOCKER_USERNAME }}/platon-discord-bot:latest
              container_name: platon-discord-bot
              environment:
                - BOT_TOKEN=\${BOT_TOKEN}
                - GEMINI_API_KEY=\${GEMINI_API_KEY}
              restart: unless-stopped
          EOL
          
          # 환경 변수 설정
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          
          # 도커 컨테이너 실행
          docker-compose pull
          docker-compose down
          docker-compose up -d
          
          # 정리
          docker image prune -af
          docker container prune -f